apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegisgate.fullname" . }}
  labels:
    {{- include "aegisgate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.wssPort }}
      targetPort: wss
      protocol: TCP
      name: wss
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "aegisgate.selectorLabels" . | nindent 4 }}
