apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aegisgate-pdb
  namespace: aegisgate
  labels:
    app.kubernetes.io/name: aegisgate
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aegisgate
      app.kubernetes.io/component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aegisgate-worker-pdb
  namespace: aegisgate
  labels:
    app.kubernetes.io/name: aegisgate
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aegisgate
      app.kubernetes.io/component: worker
