// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/bridge/gateway.go

package mocks

import (
	"context"
	"aegisguard/pkg/bridge"
)

// MockGateway is a mock implementation of the Gateway interface.
type MockGateway struct {
	ValidateRequestFunc func(request string) error
	ProcessResponseFunc  func(response string) (string, error)
}

// ValidateRequest mocks the ValidateRequest method.
func (m *MockGateway) ValidateRequest(request string) error {
	if m.ValidateRequestFunc != nil {
		return m.ValidateRequestFunc(request)
	}
	return nil
}

// ProcessResponse mocks the ProcessResponse method.
func (m *MockGateway) ProcessResponse(response string) (string, error) {
	if m.ProcessResponseFunc != nil {
		return m.ProcessResponseFunc(response)
	}
	return response, nil
}

// MockRBACManager is a mock implementation of the RBACManager interface.
type MockRBACManager struct {
	CheckPermissionFunc func(ctx context.Context, userID, resource, action string) (bool, error)
}

// CheckPermission mocks the CheckPermission method.
func (m *MockRBACManager) CheckPermission(ctx context.Context, userID, resource, action string) (bool, error) {
	if m.CheckPermissionFunc != nil {
		return m.CheckPermissionFunc(ctx, userID, resource, action)
	}
	return true, nil
}